require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/deleterequests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Deleterequest. As you add validations to Deleterequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Deleterequest.create! valid_attributes
      get deleterequests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      deleterequest = Deleterequest.create! valid_attributes
      get deleterequest_url(deleterequest)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_deleterequest_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      deleterequest = Deleterequest.create! valid_attributes
      get edit_deleterequest_url(deleterequest)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Deleterequest" do
        expect {
          post deleterequests_url, params: { deleterequest: valid_attributes }
        }.to change(Deleterequest, :count).by(1)
      end

      it "redirects to the created deleterequest" do
        post deleterequests_url, params: { deleterequest: valid_attributes }
        expect(response).to redirect_to(deleterequest_url(Deleterequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Deleterequest" do
        expect {
          post deleterequests_url, params: { deleterequest: invalid_attributes }
        }.to change(Deleterequest, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post deleterequests_url, params: { deleterequest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested deleterequest" do
        deleterequest = Deleterequest.create! valid_attributes
        patch deleterequest_url(deleterequest), params: { deleterequest: new_attributes }
        deleterequest.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the deleterequest" do
        deleterequest = Deleterequest.create! valid_attributes
        patch deleterequest_url(deleterequest), params: { deleterequest: new_attributes }
        deleterequest.reload
        expect(response).to redirect_to(deleterequest_url(deleterequest))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        deleterequest = Deleterequest.create! valid_attributes
        patch deleterequest_url(deleterequest), params: { deleterequest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested deleterequest" do
      deleterequest = Deleterequest.create! valid_attributes
      expect {
        delete deleterequest_url(deleterequest)
      }.to change(Deleterequest, :count).by(-1)
    end

    it "redirects to the deleterequests list" do
      deleterequest = Deleterequest.create! valid_attributes
      delete deleterequest_url(deleterequest)
      expect(response).to redirect_to(deleterequests_url)
    end
  end
end
